cd(@__DIR__); include("setups/simpletree.jl");
pyplot(dpi = 200)

## (a)
println("l = $(ieb1[end] - 1) and λₗ = $(𝛌[ieb1[end] - 1])")
plot(size = (200, 500), framestyle = :none)
gplot!(W, X, width = 1)
scatter_gplot!(X; marker = 𝚽[:, ieb1[end]], ms = 5)
plt = plot!(cbar = false, clims = (-0.3, 0.3))
savefig(plt, "../figs/SimpleTree_eigenvector$(ieb1[end]-1)_pink.png")

## (b)
println("l = $(ieb2[end] - 1) and λₗ = $(𝛌[ieb2[end] - 1])")
plot(size = (200, 500), framestyle = :none)
gplot!(W, X, width = 1)
scatter_gplot!(X; marker = 𝚽[:, ieb2[end]], ms = 5)
plt = plot!(cbar = false, clims = (-0.3, 0.3))
savefig(plt, "../figs/SimpleTree_eigenvector$(ieb2[end]-1)_orange.png")

## (c)
println("l = $(ieb3[end] - 1) and λₗ = $(𝛌[ieb3[end] - 1])")
plot(size = (200, 500), framestyle = :none)
gplot!(W, X, width = 1)
scatter_gplot!(X; marker = 𝚽[:, ieb3[end]], ms = 5)
plt = plot!(cbar = false, clims = (-0.3, 0.3))
savefig(plt, "../figs/SimpleTree_eigenvector$(ieb3[end]-1)_green.png")

## (d)
println("l = $(ieb4[end] - 1) and λₗ = $(𝛌[ieb4[end] - 1])")
plot(size = (200, 500), framestyle = :none)
gplot!(W, X, width = 1)
scatter_gplot!(X; marker = 𝚽[:, ieb4[end]], ms = 5)
plt = plot!(cbar = false, clims = (-0.3, 0.3))
savefig(plt, "../figs/SimpleTree_eigenvector$(ieb4[end]-1)_yellow.png")
